server:
  port: 80

spring:
#    devtools:
#        restart:
#        #激活spring-boot-devtools提供的热部署
#        enabled: true
    #SpringMVC配置视图解析
#    mvc:
#        view:
#            prefix: /WEB-INF/jsp/
#            suffix: .jsp
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/boot?useUnicode=true&characterEncoding=utf-8
        username: root
        password: root


#spring:
#  profiles:
#    #指定读取配置文件:dev(开发环境),prod(生产环境),qa(测试环境)
#    active: qa

#日志
#logging:
#  config: classpath:logback-${spring.profiles.active}.xml
#logging:
#    config: classpath:logback.xml

mybatis:
    #扫描Mybatis使用的数据表对应实体对象，使用时不用使用全包名
    type-aliases-package: com.github.springboot.example.entities
    #扫描Mybatis的主配置文件
    config-location: classpath:mybatis/mybatis-config.xml
    #扫描Mybatis的Mapper接口对应的操作SQL配置文件
    mapper-locations: classpath:mybatis/mapper/*.xml