#spring:
#    devtools:
#        restart:
#        #激活spring-boot-devtools提供的热部署
#        enabled: true
    #SpringMVC配置视图解析
#    mvc:
#        view:
#            prefix: /WEB-INF/jsp/
#            suffix: .jsp

#spring:
#  profiles:
#    #指定读取配置文件:dev(开发环境),prod(生产环境),qa(测试环境)
#    active: qa

#日志
#logging:
#  config: classpath:logback-${spring.profiles.active}.xml
#logging:
#    config: classpath:logback.xml